server:
   port: 9090
   



management:
      endpoints:
         web:
           exposure:
              include: "*"   

#----application config------------
pinManager:
    invalidCount: 3
    maxPinRemovalDuration: 1h

              
#---------------------H2 DB config----------------------
spring:
   datasource:
            url: jdbc:h2:mem:pinManageDB
            #url: jdbc:h2:mem:file:D:/h2-db/data
            driverClassName: org.h2.Driver
            username: sa
            password: password
   jpa:
     show-sql: true
     
     properties:
                 hibernate:
                           dialect: org.hibernate.dialect.H2Dialect
     hibernate:
              ddl-auto: update
   h2:
     console:
           enabled: true
           path: /h2-console
           setting:
                   trace: false
                   web-allow-others: false
   
   logging:
    file: logs/dev_app.log
    pattern:
        console: "%d %-5level %logger : %msg%n"
        file: "%d %-5level [%thread] %logger : %msg%n"
    level:
    org.springframework.web: DEBUG
    com.docomo.pinmanager.services: DEBUG
    org.hibernate: DEBUG


         
     